name: login
 
on:
 
  push:
   branches: [ "main" ]
  pull_request:
   branches: [ "main" ]
 
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
      - name: Setup 2 Install Newman-Reporter-Htmlextra
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
 
      - name: Step 3 execute TESTE
        run: npm install -g newman-reporter-htmlextra
 
      - name: Step 3 Execute collection
        run: newman run ./2_login.json -e ./variaveis.json -g ./globals.json --delay-request 1 --reporters cli, -r htmlextra --reporter-htmlextra-export ./result/report.html
 
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./result/Report.html
